use myapp;

CREATE TABLE  E_CAR
   (CAR_ID VARCHAR(500) unique, 
	MODEL_NAME VARCHAR(500), 
	MANUFACTURING_YEAR VARCHAR(500),
    MILEAGE FLOAT,
	SEATING_CAPACITY INT, 
    PRICE_PER_DAY INT,
	QUANTITY INT, 
	ISSUED INT, 
	 CONSTRAINT E_CAR_PK PRIMARY KEY (CAR_ID)
   );
   
CREATE TABLE  E_CARPROVIDER
   (ID INT AUTO_INCREMENT, 
	FULL_NAME VARCHAR(500),
	EMAIL VARCHAR(500) unique not null,
    PASSWORD VARCHAR(500) unique not null, 
	MOBILE VARCHAR(15) unique, 
    CONSTRAINT E_CUSTOMER_PK PRIMARY KEY (ID)
   )
;

-- Note: ID must be generated through sequence in E_CARPROVIDER table.

CREATE TABLE  E_ISSUECAR
   (CAR_ID VARCHAR(500) NOT NULL, 
	CUSTOMERID VARCHAR(500) NOT NULL, 
	CUSTOMERNAME VARCHAR(500) NOT NULL, 
    LICENSENUMBER VARCHAR(500) UNIQUE NOT NULL,
	CUSTOMERMOBILE BIGINT UNIQUE, 
	ISSUEDDATE DATE, 
	RETURNSTATUS VARCHAR(500)
   );